project_id = "wafhzujgjvetexwohpgy"

[functions.list-users]
verify_jwt = false

[functions.create-user]
verify_jwt = false

[functions.update-user]
verify_jwt = false

[functions.reset-user-password]
verify_jwt = false
